#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtcharts
Version  : 5.10.1
Release  : 6
URL      : http://download.qt.io/official_releases/qt/5.10/5.10.1/submodules/qtcharts-everywhere-src-5.10.1.tar.xz
Source0  : http://download.qt.io/official_releases/qt/5.10/5.10.1/submodules/qtcharts-everywhere-src-5.10.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: qtcharts-lib
BuildRequires : cmake
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Multimedia)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras

%description
---------------
Qt Charts
---------------
Qt Charts module provides a set of easy to use chart components. It uses
the Qt Graphics View Framework, therefore charts can be easily integrated
to modern user interfaces.

%package dev
Summary: dev components for the qtcharts package.
Group: Development
Requires: qtcharts-lib
Provides: qtcharts-devel

%description dev
dev components for the qtcharts package.


%package lib
Summary: lib components for the qtcharts package.
Group: Libraries

%description lib
lib components for the qtcharts package.


%prep
%setup -q -n qtcharts-everywhere-src-5.10.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
qmake QMAKE_CFLAGS="$CFLAGS" QMAKE_CXXFLAGS="$CXXFLAGS" QMAKE_LFLAGS="$LDFLAGS" \
    QMAKE_CFLAGS_RELEASE= QMAKE_CXXFLAGS_RELEASE=
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
make INSTALL_ROOT=%{buildroot} install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/abstractbarchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/abstractchartlayout_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/abstractdomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/areachartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/axisanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/bar_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/baranimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/barchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/boxplotanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/boxplotchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/boxwhiskers_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/boxwhiskersanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/boxwhiskersdata_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/candlestick_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/candlestickanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/candlestickbodywicksanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/candlestickchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/candlestickdata_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/cartesianchartaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/cartesianchartlayout_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartaxiselement_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartbackground_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartbarcategoryaxisx_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartbarcategoryaxisy_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartcategoryaxisx_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartcategoryaxisy_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartconfig_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartdataset_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartdatetimeaxisx_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartdatetimeaxisy_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartelement_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/charthelpers_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartlogvalueaxisx_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartlogvalueaxisy_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartpresenter_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/charttheme_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemebluecerulean_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemeblueicy_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemebluencs_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemebrownsand_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemedark_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemehighcontrast_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemelight_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthememanager_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemeqt_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartthemesystem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/charttitle_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartvalueaxisx_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/chartvalueaxisy_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/glwidget_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/glxyseriesdata_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/horizontalaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/horizontalbarchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/horizontalpercentbarchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/horizontalstackedbarchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/legendlayout_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/legendmarkeritem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/legendscroller_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/linearrowitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/linechartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/logxlogydomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/logxlogypolardomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/logxydomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/logxypolardomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/percentbarchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/pieanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/piechartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/piesliceanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/pieslicedata_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/piesliceitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartaxisangular_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartaxisradial_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartcategoryaxisangular_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartcategoryaxisradial_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartdatetimeaxisangular_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartdatetimeaxisradial_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartlayout_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartlogvalueaxisangular_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartlogvalueaxisradial_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartvalueaxisangular_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polarchartvalueaxisradial_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/polardomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qabstractaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qabstractbarseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qabstractseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qarealegendmarker_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qareaseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qbarcategoryaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qbarlegendmarker_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qbarmodelmapper_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qbarseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qbarset_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qboxplotlegendmarker_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qboxplotmodelmapper_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qboxplotseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qboxset_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qcandlesticklegendmarker_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qcandlestickmodelmapper_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qcandlestickseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qcandlestickset_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qcategoryaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qchart_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qchartglobal_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qchartview_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qdatetimeaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qhorizontalbarseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qhorizontalpercentbarseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qhorizontalstackedbarseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qlegend_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qlegendmarker_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qlineseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qlogvalueaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qpercentbarseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qpielegendmarker_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qpiemodelmapper_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qpieseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qpieslice_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qscatterseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qsplineseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qstackedbarseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qvalueaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qxylegendmarker_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qxymodelmapper_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/qxyseries_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/scatteranimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/scatterchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/scroller_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/splineanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/splinechartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/stackedbarchartitem_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/verticalaxis_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/xlogydomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/xlogypolardomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/xyanimation_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/xychart_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/xydomain_p.h
/usr/include/qt5/QtCharts/5.10.1/QtCharts/private/xypolardomain_p.h
/usr/include/qt5/QtCharts/QAbstractAxis
/usr/include/qt5/QtCharts/QAbstractBarSeries
/usr/include/qt5/QtCharts/QAbstractSeries
/usr/include/qt5/QtCharts/QAreaLegendMarker
/usr/include/qt5/QtCharts/QAreaSeries
/usr/include/qt5/QtCharts/QBarCategoryAxis
/usr/include/qt5/QtCharts/QBarLegendMarker
/usr/include/qt5/QtCharts/QBarModelMapper
/usr/include/qt5/QtCharts/QBarSeries
/usr/include/qt5/QtCharts/QBarSet
/usr/include/qt5/QtCharts/QBoxPlotLegendMarker
/usr/include/qt5/QtCharts/QBoxPlotModelMapper
/usr/include/qt5/QtCharts/QBoxPlotSeries
/usr/include/qt5/QtCharts/QBoxSet
/usr/include/qt5/QtCharts/QCandlestickLegendMarker
/usr/include/qt5/QtCharts/QCandlestickModelMapper
/usr/include/qt5/QtCharts/QCandlestickSeries
/usr/include/qt5/QtCharts/QCandlestickSet
/usr/include/qt5/QtCharts/QCategoryAxis
/usr/include/qt5/QtCharts/QChart
/usr/include/qt5/QtCharts/QChartGlobal
/usr/include/qt5/QtCharts/QChartView
/usr/include/qt5/QtCharts/QDateTimeAxis
/usr/include/qt5/QtCharts/QHBarModelMapper
/usr/include/qt5/QtCharts/QHBoxPlotModelMapper
/usr/include/qt5/QtCharts/QHCandlestickModelMapper
/usr/include/qt5/QtCharts/QHPieModelMapper
/usr/include/qt5/QtCharts/QHXYModelMapper
/usr/include/qt5/QtCharts/QHorizontalBarSeries
/usr/include/qt5/QtCharts/QHorizontalPercentBarSeries
/usr/include/qt5/QtCharts/QHorizontalStackedBarSeries
/usr/include/qt5/QtCharts/QLegend
/usr/include/qt5/QtCharts/QLegendMarker
/usr/include/qt5/QtCharts/QLineSeries
/usr/include/qt5/QtCharts/QLogValueAxis
/usr/include/qt5/QtCharts/QPercentBarSeries
/usr/include/qt5/QtCharts/QPieLegendMarker
/usr/include/qt5/QtCharts/QPieModelMapper
/usr/include/qt5/QtCharts/QPieSeries
/usr/include/qt5/QtCharts/QPieSlice
/usr/include/qt5/QtCharts/QPolarChart
/usr/include/qt5/QtCharts/QScatterSeries
/usr/include/qt5/QtCharts/QSplineSeries
/usr/include/qt5/QtCharts/QStackedBarSeries
/usr/include/qt5/QtCharts/QVBarModelMapper
/usr/include/qt5/QtCharts/QVBoxPlotModelMapper
/usr/include/qt5/QtCharts/QVCandlestickModelMapper
/usr/include/qt5/QtCharts/QVPieModelMapper
/usr/include/qt5/QtCharts/QVXYModelMapper
/usr/include/qt5/QtCharts/QValueAxis
/usr/include/qt5/QtCharts/QXYLegendMarker
/usr/include/qt5/QtCharts/QXYModelMapper
/usr/include/qt5/QtCharts/QXYSeries
/usr/include/qt5/QtCharts/QtCharts
/usr/include/qt5/QtCharts/QtChartsDepends
/usr/include/qt5/QtCharts/QtChartsVersion
/usr/include/qt5/QtCharts/chartsnamespace.h
/usr/include/qt5/QtCharts/qabstractaxis.h
/usr/include/qt5/QtCharts/qabstractbarseries.h
/usr/include/qt5/QtCharts/qabstractseries.h
/usr/include/qt5/QtCharts/qarealegendmarker.h
/usr/include/qt5/QtCharts/qareaseries.h
/usr/include/qt5/QtCharts/qbarcategoryaxis.h
/usr/include/qt5/QtCharts/qbarlegendmarker.h
/usr/include/qt5/QtCharts/qbarmodelmapper.h
/usr/include/qt5/QtCharts/qbarseries.h
/usr/include/qt5/QtCharts/qbarset.h
/usr/include/qt5/QtCharts/qboxplotlegendmarker.h
/usr/include/qt5/QtCharts/qboxplotmodelmapper.h
/usr/include/qt5/QtCharts/qboxplotseries.h
/usr/include/qt5/QtCharts/qboxset.h
/usr/include/qt5/QtCharts/qcandlesticklegendmarker.h
/usr/include/qt5/QtCharts/qcandlestickmodelmapper.h
/usr/include/qt5/QtCharts/qcandlestickseries.h
/usr/include/qt5/QtCharts/qcandlestickset.h
/usr/include/qt5/QtCharts/qcategoryaxis.h
/usr/include/qt5/QtCharts/qchart.h
/usr/include/qt5/QtCharts/qchartglobal.h
/usr/include/qt5/QtCharts/qchartview.h
/usr/include/qt5/QtCharts/qdatetimeaxis.h
/usr/include/qt5/QtCharts/qhbarmodelmapper.h
/usr/include/qt5/QtCharts/qhboxplotmodelmapper.h
/usr/include/qt5/QtCharts/qhcandlestickmodelmapper.h
/usr/include/qt5/QtCharts/qhorizontalbarseries.h
/usr/include/qt5/QtCharts/qhorizontalpercentbarseries.h
/usr/include/qt5/QtCharts/qhorizontalstackedbarseries.h
/usr/include/qt5/QtCharts/qhpiemodelmapper.h
/usr/include/qt5/QtCharts/qhxymodelmapper.h
/usr/include/qt5/QtCharts/qlegend.h
/usr/include/qt5/QtCharts/qlegendmarker.h
/usr/include/qt5/QtCharts/qlineseries.h
/usr/include/qt5/QtCharts/qlogvalueaxis.h
/usr/include/qt5/QtCharts/qpercentbarseries.h
/usr/include/qt5/QtCharts/qpielegendmarker.h
/usr/include/qt5/QtCharts/qpiemodelmapper.h
/usr/include/qt5/QtCharts/qpieseries.h
/usr/include/qt5/QtCharts/qpieslice.h
/usr/include/qt5/QtCharts/qpolarchart.h
/usr/include/qt5/QtCharts/qscatterseries.h
/usr/include/qt5/QtCharts/qsplineseries.h
/usr/include/qt5/QtCharts/qstackedbarseries.h
/usr/include/qt5/QtCharts/qtchartsversion.h
/usr/include/qt5/QtCharts/qvalueaxis.h
/usr/include/qt5/QtCharts/qvbarmodelmapper.h
/usr/include/qt5/QtCharts/qvboxplotmodelmapper.h
/usr/include/qt5/QtCharts/qvcandlestickmodelmapper.h
/usr/include/qt5/QtCharts/qvpiemodelmapper.h
/usr/include/qt5/QtCharts/qvxymodelmapper.h
/usr/include/qt5/QtCharts/qxylegendmarker.h
/usr/include/qt5/QtCharts/qxymodelmapper.h
/usr/include/qt5/QtCharts/qxyseries.h
/usr/lib64/cmake/Qt5Charts/Qt5ChartsConfig.cmake
/usr/lib64/cmake/Qt5Charts/Qt5ChartsConfigVersion.cmake
/usr/lib64/libQt5Charts.la
/usr/lib64/libQt5Charts.prl
/usr/lib64/libQt5Charts.so
/usr/lib64/pkgconfig/Qt5Charts.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5Charts.so.5
/usr/lib64/libQt5Charts.so.5.10
/usr/lib64/libQt5Charts.so.5.10.1
/usr/lib64/qt5/qml/QtCharts/designer/ChartViewSpecifics.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/AreaSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/BarSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/BoxPlotSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/HorizontalBarSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/HorizontalPercentBarSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/HorizontalStackedBarSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/LineSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/PercentBarSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/PieSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/PolarAreaSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/PolarLineSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/PolarScatterSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/PolarSplineSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/ScatterSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/SplineSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/default/StackedBarSeries.qml
/usr/lib64/qt5/qml/QtCharts/designer/images/areaseries-chart-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/areaseries-chart-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/areaseries-polar-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/areaseries-polar-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/barseries-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/barseries-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/boxplotseries-chart-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/boxplotseries-chart-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/horizontalbarseries-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/horizontalbarseries-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/horizontalpercentbarseries-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/horizontalpercentbarseries-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/horizontalstackedbarseries-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/horizontalstackedbarseries-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/lineseries-chart-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/lineseries-chart-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/lineseries-polar-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/lineseries-polar-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/percentbarseries-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/percentbarseries-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/pieseries-chart-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/pieseries-chart-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/scatterseries-chart-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/scatterseries-chart-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/scatterseries-polar-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/scatterseries-polar-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/splineseries-chart-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/splineseries-chart-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/splineseries-polar-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/splineseries-polar-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/images/stackedbarseries-icon.png
/usr/lib64/qt5/qml/QtCharts/designer/images/stackedbarseries-icon16.png
/usr/lib64/qt5/qml/QtCharts/designer/qtcharts.metainfo
/usr/lib64/qt5/qml/QtCharts/libqtchartsqml2.so
/usr/lib64/qt5/qml/QtCharts/plugins.qmltypes
/usr/lib64/qt5/qml/QtCharts/qmldir
